### ISSUE TITLE
bug 与期望

### ISSUE THREAD

**Issue by David-Guo** [tnmichael309/Network-Programming#1]
师兄你好，我选修了这学期的 NP 课，用C 的链表结构实现了多级 pipe 和网络链接部分，代码在我的repository 里面。但是在看了你的代码之后，觉得自己设计的太差劲了。希望能基于你的架构再实现一个C++版的，并将新的功能  `! num`   加进去。

顺便提一个bug：你的 shell.cpp 文件里190行 可能存在内存泄漏问题，new 出来的 argv 没有释放。

**Comment by tnmichael309** [comment]
@David-Guo 嗨 請不要這麼做 架構可以參考，但是必須都自己寫，寫得太像，別人也可能參考，這樣可能會被判斷為抄襲!
